version: '3.1'
services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    networks:
      - flink-network
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6.0
    container_name: kafka
    networks:
      - flink-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Updated to use internal Docker DNS
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jobmanager:
    image: flink:latest
    container_name: flink-jobmanager
    networks:
      - flink-network
    ports:
      - "8081:8081"  # Flink Web UI
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: jobmanager

  taskmanager:
    image: flink:latest
    container_name: flink-taskmanager
    networks:
      - flink-network
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: taskmanager

networks:
  flink-network:
